import { BooksTable } from "@/modules/Librarian/presentation/components/BooksTable";
import React from "react";

const page = () => {
  const mockBooks = [
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
    {
      id: "1",
      title: "HarryPotter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      bookNumber: "dss_342",
      publication: "XYZ Publication House",
      isbn: "324737429381",
      price: "Rs. 300",
    },
  ];
  return <BooksTable data={mockBooks} />;
};

export default page;
