import { ST } from "next/dist/shared/lib/utils";

export const QueryKeys = {
  LOGIN: "login",
  STUDENTDASHBOARD: "student-dashboard",
  LIBRARIANDASHBOARD: "librarian-dashboard",
  FEEDBACKS: "feedbacks",
  USERS: "users",
  QUOTES: "quotes",
  EVENTS: "events",
  ANNOUNCEMENTS: "announcements",
  ISSUES: "issue-book",
  RECOMMENDATIONS: "recommendations",
  STUDENTPROFILE: "student-profile",
  BOOKS: "books",
  GENRES: "genre",
  BOOKMARKS: "bookmark",
  REVIEWS: "reviews",
  BORROWBOOKS: "book-borrow",
  RESERVES: "reserves",
  AVAILABLECOPIES: "available-book-copies",
  DASHBOARDSTATS: "dashboard-stats",
  TOPOVERDUES: "top-overdues",
  TOPBOOKSBORROWED: "top-books-borrowed",
  RECENTLYISSUEDBOOKS: "recently-issued-books",
};
